### ISSUE TITLE
只能在群里使用，无法在好友里用

### ISSUE THREAD

**Issue by Dingtaiqi** [WJZ-P/LiteLoaderQQNT-Stick-Emoji#2]
QQ版本9.9.16
贴表情只能在群里贴
![image](https://github.com/user-attachments/assets/91e5e27d-0824-451f-a5eb-20f12c46234d)

好友里贴不了

![image](https://github.com/user-attachments/assets/c8428fdc-b9fb-4829-83c5-c2c0bc024f9c)

**Comment by WJZ-P** [comment]
已修复。这个是显示bug，好友列表不应该出现贴表情，因为QQ只支持群聊贴表情
