### ISSUE TITLE
BUG: 插件不生效

### ISSUE THREAD

**Issue by Alan-CRL** [WJZ-P/LiteLoaderQQNT-Stick-Emoji#5]
我现在并不清楚这个插件启用后是什么效果。不过根据我的观察，聊天框和右键菜单都没有任何变化，这似乎是没有生效。还有就是 QQNT 的版本是老版本，而我使用的是 arm win11，升级后就没有适配版本的 DLLHijackMethod 了，所以希望可以修复这个版本的问题。同时也有可能是和其他插件冲突导致的吧，不过右键菜单是一点变化都没有。

![QQ_1Tgj9Fchnf](https://github.com/user-attachments/assets/89e3c4ad-8e25-41fe-8e80-7e8a1a927e3f)

**Comment by WJZ-P** [comment]
你可以手动给别人贴表情看看，arm架构下我不清楚会不会有问题，我没有arm的机器，无法做测试。右键菜单按理说如果轻量工具箱的右键菜单可以正常有选项，我这个应该也可以，因为我是参考他的来写的

**Comment by Alan-CRL** [comment]
应该不是 arm 的问题，因为我装的是 x64 版本的 qqnt。如果需要复现，可以尝试下载 QQNT 9.9.15-27597 试试。这个应该是新版大改文件布局前的最后一个版本。

**Comment by Alan-CRL** [comment]
@WJZ-P 我重新安装了 QQNT，现在正常了。

**Comment by WJZ-P** [comment]
> @WJZ-P 我重新安装了 QQNT，现在正常了。
![2cb05d502927a00d8f0c9f97a95f0026](https://github.com/user-attachments/assets/eff9e9d2-dea0-440b-b553-52e5dd7a37ef)
